{"version":3,"sources":["test/fixture/initial-source-map-exception.js"],"names":[],"mappings":";;AAAA,IAAM,IAAI,GAAG,OAAO,CAAC,QAAQ,CAAC,CAAC;;AAE/B,IAAI,CAAC,6BAA6B,EAAE,UAAA,CAAC,EAAI;AACxC,aAAY,CAAC,GAAG,CAAC,CAAC;CAClB,CAAC,CAAC;;AAEH,SAAS,GAAG,GAAG;AACd,IAAG,EAAE,CAAC;CACN;;AAED,SAAS,GAAG,GAAG;AACd,OAAM,IAAI,KAAK,oBAAmB,CAAA;CAClC","file":"test/fixture/initial-source-map-exception.js","sourcesContent":["const test = require('../../');\n\ntest('throw an uncaught exception', t => {\n\tsetImmediate(foo);\n});\n\nfunction foo() {\n\tbar();\n}\n\nfunction bar() {\n\tthrow new Error(`Can't catch me!`)\n}\n"]}
